apiVersion: kubeless.io/v1beta1
kind: Function
metadata: 
  labels: 
    k8s-app: metrics
    example: monitoring-alert-rules
  name: sample-metrics
  namespace: default
spec: 
  deployment: 
    metadata: 
      name: sample-metrics
      namespace: default
    spec:
      replicas: 2 
      template: 
        spec: 
          containers: 
            - 
              name: sample-metrics
              resources: 
                limits: 
                  cpu: 100m
                  memory: 100Mi
                requests: 
                  cpu: 100m
                  memory: 100Mi
  deps: ""
  function: |
      module.exports = {
        myLambda: function(event, context) {
          return event.data;
        }
      }
  handler: test.myLambda
  runtime: nodejs8
  type: HTTP