kind: Service
apiVersion: v1
metadata:
  name: sample-metrics-8080
  namespace: default
  labels:
    example: monitoring-custom-metrics
spec:
  selector:
    app: sample-metrics
  ports:
  - name: web
    port: 8080
    protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: sample-metrics-8081
  labels:
    k8s-app: metrics
    example: monitoring-custom-metrics
  namespace: default
spec:
  selector:
    app: sample-metrics
  ports:
  - name: web
    port: 8081
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-metrics
  namespace: default
spec:
  replicas: 4
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"    
        traffic.sidecar.istio.io/includeInboundPorts: "8080"  
      labels:
        app: sample-metrics
        example: monitoring-custom-metrics
        version: 1.1.3
    spec:
      containers:
      - name: sample-metrics
        image: sample-metrics-app:latest
        imagePullPolicy: IfNotPresent
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics
  namespace: kyma-system
  labels:
    prometheus: core
    example: monitoring-custom-metrics
spec:
  selector:
    matchLabels:
      k8s-app: metrics
  targetLabels:
    - k8s-app
  endpoints:
  - port: web
    interval: 10s
  namespaceSelector:
    matchNames:
      - default